### ISSUE TITLE
Pigments is not reloaded when switching between projects

### ISSUE THREAD

**Issue by Goldskin** [jccguimaraes/atom-project-viewer#133]
# ISSUE
Hello, 
there's a problem when i'm switching project: if there's a color in a scss variable, and it's a the same name between the two, the wrong color is shown in the code

## Environment
- **OS**: OSX;
- **Atom**: 1.14.4;

## Steps
Open a project with a scss variable ($color-primary), then switch to a second project with the same scss variable ($color-primary), it's the first project's color.

**Comment by jccguimaraes** [comment]
hey @Goldskin,

thanks for pointing this out. I think the problem here is from the the serialization/deserialization of atom. without an actual reload / restart, some of the packages, are obviously on the atom's core funcitonality.

I managed to make linter (by a hack) restart i believe, but yes, i need to find a more dynamic way to reattach / restart / reset / wtv plugins that are active on each person.

I need a lot of investigation, if you don't mind waiting i would appreciate it.

Contributions are always welcome :)

:+1: for pointing this out

**Comment by jccguimaraes** [comment]
hey @Goldskin is this option ok with you?

![listofpackages](https://cloud.githubusercontent.com/assets/14871650/26285893/55d2bd84-3e50-11e7-9932-c251d6e9d009.png)

If this is ok, will ship it in the next release.

**Comment by jccguimaraes** [comment]
please check new version `1.1.0` and provide feedback if possible.
