### ISSUE TITLE
DISCUSSION: Refactor to use ETCH

### ISSUE THREAD

**Issue by jccguimaraes** [jccguimaraes/atom-project-viewer#145]
One of the main reasons this package takes to long to go out on major releases is that one of the things I didn't want to use was jquery (and in this case, atom-space-pen wtv). 

As stated

> Etch is a library for writing HTML-based user interface components that provides the convenience of a virtual DOM, while at the same time striving to be minimal, interoperable, and explicit. Etch can be used anywhere, but it was specifically designed with Atom packages and Electron applications in mind.
> 
> Overview
> 
> Etch components are ordinary JavaScript objects that conform to a minimal interface. Instead of inheriting from a superclass or building your component with a factory method, you access Etch's functionality by passing your component to Etch's library functions at specific points of your component's lifecycle. A typical component is structured as follows:

So what do you think making this huge refactor for the sake of the community?

**Pros:**
- will reduce a lot of code
- will make it easier for new comers to contribute

**Cons:**
- big ass refactor (again)

Give me your thoughts!

**Comment by Hammster** [comment]
I agree jQuery is an unnecessary library in atom, and in my opinion in general web by now. I absolutely approve your view there.

I really like the idea to make the system simpler without introducing too much non-js type domain specific languages. One thing I dislike on etch is that render function because this does the opposite of this.

__Example__
``` javascript
render() {
  <div>
      <h1>I am a parent</div>
      <ChildComponent adjective='good'>
          <div>Grandchild 1</div>
          <div>Grandchild 2</div>
      <ChildComponent/>
  </div>
}
```
`<ChildComponent adjective='good'>` may is expressive but it is also something people have to learn in order to understand the purpose. 

In addition to that mixing HTML and JS breaks default tooling, I mean why adding JSX to JS if JS could do the same thing. I am aware that etch is a package made and maintained by atom, but this really gives me the shivers, same as they include jQuery in atom-space-pen-views. I have this same view on react too. 

So there are additional costs coming with this kind of approche, besides the refactor. And it may end up doing the opposite of simplifying the project.

__Summarized:__ I like the idea, but I can foresee some additional cons that may be higher than the gain from using it. Maybe we can archive the same goal with native JS or something that does not bring in such costs.

**Comment by bfis** [comment]
I would strongly suggest you to take a closer look at [vue.js](https://vuejs.org/).
It's a joy to work with, because you can very quickly implement user-interfaces.

**Comment by jccguimaraes** [comment]
The question here is that Etcher is "native" to Atom. Like space-atom was before. But it's all on the table

**Comment by bfis** [comment]
If you are considering to refactor, to cut down the (coding)time to interact with the DOM, you may want to go all the way. Etch appears still a little bit raw (as in close to raw DOM manipulation).

**Comment by Hammster** [comment]
Well I'm coding a lot in vue and I can approve on @bfis statement. But for our needs even vue delivers a lot of overhead, we only need the Virtual DOM and the data bindings which are pretty simple to implement and none of the templating features, extended lifecycle or server-side rendering.

**Comment by jccguimaraes** [comment]
closing, this will be discussed for new major version
