### ISSUE TITLE
Paths folder changing alone

### ISSUE THREAD

**Issue by nbdamian** [jccguimaraes/atom-project-viewer#158]
# Issue
When I am switching between different projects, the project path is changing for another project or sometimes disappear.

## Environment
- **OS**:Windows 10;
- **Atom**: 1.18.0 ia32;
- Any other particularity;

## Steps
Switching between different projects

![pathfolder-disapear](https://user-images.githubusercontent.com/16768293/27460830-6f9710de-580a-11e7-87b9-13044f03746a.jpg)

**Comment by jccguimaraes** [comment]
thanks for reporting this. i will try to fix this issue.

**Comment by Miguel-F** [comment]
@jccguimaraes this may be the same issue I was reporting in https://github.com/jccguimaraes/atom-project-viewer/issues/155 where once I switch to another project, I cannot re-open the first project. The folders in the project-viewer panel sometimes (not every time) look like the image posted here (with the grayed out name and strikethrough).

**Comment by jccguimaraes** [comment]
@Miguel-F finally have a time to address this. ok. so when you see a project crossed that means that the project has no paths associated.

This is an issue because i did had this a while ago and don't know if it is related to all this Atom's internal changes and messing with the saved context.

So, for now try to clear all files under `~/.atom/storage` that starts with the word `editor`. This will remove all saved states and start a fresh state context saving.

I will investigate if something else is happening

**Comment by jccguimaraes** [comment]
Also i made some changes and up to now, i didn't have this issue anymore. Will try to fix some more bugs to i release a more stable version.

**Comment by jccguimaraes** [comment]
please validate this issue!

**Comment by jccguimaraes** [comment]
Thanks =}
