### ISSUE TITLE
I lost all my Groups and Projects

### ISSUE THREAD

**Issue by tarikkavaz** [jccguimaraes/atom-project-viewer#32]
All of a sudden all my Groups and Projects disappeared. How am I supposed to get them back?

**Comment by jccguimaraes** [comment]
hi @tarikkavaz in what version are you?
As this is saved on a file and if you edit it and it's empty i am affraid but it's lost :(
Although it should not happen in last release, I am working on a safer file/db manager.

Sorry for this :(

**Comment by tarikkavaz** [comment]
Hi João 
Thanks for the quick reply

Atom 1.5.3
project-viewer 0.2.31

Btw I didn't open/edit or any kind of files 
Hope we can make it work 


Tarık Kavaz

On 29 February 2016 at 11:02:53, João Guimarães (notifications@github.com) wrote:

hi @tarikkavaz in what version are you?
As this is saved on a file and if you edit it and it's empty i am affraid but it's lost :(
Although it should not happen in last release, I am working on a safer file/db manager.

Sorry for this :(

**Comment by jccguimaraes** [comment]
Can you go to `Packages -> Project Viewer -> Edit file`? It will open the db file, and please check if something is in there. But if you are using latest version, i believe you have lost everything :/ damn

**Comment by tarikkavaz** [comment]
I have no db file, it's gone I guess. damn

**Comment by jccguimaraes** [comment]
sorry about that :((((((((

**Comment by bkcsoft** [comment]
Not sure if it's related to this bug but the result was the same, groups and projects went bye bye :unamused: 

The cause was that my disk was full so `project-viewer.json` got trunkated. That in itself isn't the bug though, the bug is that project-viewer/atom didn't notify me that the write was incomplete :angry: 

Like I said, not sure if this is the same bug (or similar), I can open a specific issue if necessary :smiley:

**Comment by jccguimaraes** [comment]
Damn @bkcsoft :(
I am implementing the atom.storage that itself creates a file in the storage folder and I hope they did a good handling on this.
No matter this new aproach, i will also implement an option for backup to an outsider file or other solution.

There will not be an option for edit the file though.

Do you think this is not a good solution? @bkcsoft and @tarikkavaz.

**Comment by tarikkavaz** [comment]
Maybe you can use [gist](https://gist.github.com/) like [Sync Settings for Atom](https://github.com/Hackafe/atom-sync-settings).

**Comment by jccguimaraes** [comment]
hey @tarikkavaz thanks for the share.
definilty will have a look at it

**Comment by camlafit** [comment]
Hi

On Debian Jessie with last atom and project-viewer

On crash system if Atom is opened, project-viewer.json is emptied.
A temporary solution may be to have an automatic backup file.

I presume this file is in open status when Atom session is active. In this case with a simple crash, full disk, ... this file can be purged.

**Comment by jccguimaraes** [comment]
hi @camlafit 
yes backup solution is an option on next big release/refactor.
I am deeply sorry for this as there's no solution as it is.
Just ask you for now to backup the file manually please...to be safe

**Comment by vanboom** [comment]
:+1: Same here... all projects and groups lost somehow.  A temporary solution is to backup your ~/.atom/project-viewer.json file any time you add/remove projects.

**Comment by jccguimaraes** [comment]
Hey @vanboom,
Sorry for this behaviour, I know it sucks :(
I think that somewhere along the validation the package gets all cranky and deletes everything..

Have been diging the atom api and other packages and i am using the `atom.storageFolder().load` and `atom.storageFolder().store` for the I/O of the file. I guess they did manage to make it stable.

Also, the saving on add/remove projects / groups is already implemented. The problem is the tree-view state that does not emit anything if changed (like collapse a folder, etc) so, that is a problem I haven't found a good solution. Saving it from time to time is a nasty hack... saving in on the destroy /deactivate of the package / Atom is also a bad hack...

So it's taking more time that I antecipated...
