### ISSUE TITLE
ISSUE: New projects are gone after restart

### ISSUE THREAD

**Issue by Duncank** [jccguimaraes/atom-project-viewer#47]
Since the latest update (0.3.2) projects I add are gone when I restart Atom. This happens both when I add a new client or group and a new project in one of those, and when I add a new project to an existing group.

This bug could have been present on earlier versions in the 0.3.X range, I think I skipped a version while updating.

I'm using Atom 1.8.0 on Windows 10.

**-- EDIT -- I've disabled "convert old data" in the package-settings and now my new projects remain after restart. Maybe this should be toggled automatically after the first restart after updating to 0.3.X**

**Comment by jccguimaraes** [comment]
hi @Duncank,
So the main reason for that option is that previous to `0.3.0` there was an older version database, as well as where it was being stored.
By default, it will check if the old file exists and try to convert to the new one if the new store isn't available. Making it to `false` will assume you didn't have the old database or it has already been converted. It will not import/convert the old if you have anything created on the new.

Please validate that you still have the old file (a notification pops up saying it could not find it. If another notification says I believe could not convert that's because there is a new database.

Confused?

**Comment by jccguimaraes** [comment]
the notification pops up if the option is `false`.

**Comment by Duncank** [comment]
I had notifications disabled in Atom, since a few packages where giving me a lot of unneccessary notifications. With notifications enabled, I indeed see the message to disable the "convert old data" setting.

When I tried this, I checked Convert old data again and on restart it restored my projects back to the ones I had before v0.3. So my new projects on the new database only remain after a restart when Convert old data is unchecked.

**Comment by jccguimaraes** [comment]
so you lost the new not the old right?

**Comment by Duncank** [comment]
That's correct

**Comment by jccguimaraes** [comment]
it should try but not be able to because it has already new data... ok now i have understand the issue. Thanks.

To be clear about the workflow:

- If no new data:
  - If no old file, list is empty (safe to disable option)
  - If old file, the list is populated with it. (if conversion is ok, safe to disable and delete the file (from the package menu)

- If new data:
  - If no old file, list with new date (safe to disable option)
  - If old file, will try find the old file and convert to the new but (should not be able to) and inform the user about this (if you don't care about the old date, safe to disable the option and probably delete the old file)

[] Validate last assuption

**Comment by Duncank** [comment]
On restart of Atom there are 3 possible scenarios:
1. "convert old data" checked (default), new projects created last time
    newly created projects are gone after restart. List is populated with old projects. (not correct)
2. "convert old data" checked (default), no new projects created last time
    list is populated with old projects (correct)
3. "convert old data" unchecked
    new projects that I create will stay in the list after the next restart (correct)

I'm afraid that when I delete the old project file they will be gone again in the future, so I'd rather keep that for now.

**Comment by jccguimaraes** [comment]
until i reach that stability, it's better to disabled the option and don't delete the file yes.

**Comment by jccguimaraes** [comment]
and also sorry for that :(

**Comment by jccguimaraes** [comment]
Please validate if this still occurs.
Your feedback is vital 👌 
Thanks.

**Comment by Duncank** [comment]
It doesn't delete new projects anymore after a restart when "convert old data" is checked, nice! It did however create a copy of all existing groups and projects, so I guess it converted them again.

I manually deleted all those doubled groups and after a restart everything shows up like it should. Thanks for the update!
