### ISSUE TITLE
ISSUE: Does not open left-aligned on first load

### ISSUE THREAD

**Issue by ShiroiKuma** [jccguimaraes/atom-project-viewer#67]
# ISSUE
When opening Atom with project-viewer set to display on the left, it odes not always open on the left. It mostly opens up on the right side of the documents tree.

## Environment
- **OS**: ...; Mac OSX El Capitan 10.11.5
- **Atom**: ...; 1.8.0

## Steps
Open Atom and notice the project-viewer is to the right of the documents tree.
Close but don't quit
Re-open from the Dock and it now displays on the left as expected.

If you 'quit' Atom completely, then re-open. The issue appears again.

**Comment by DamnedScholar** [comment]
For clarification: it's *always* displaying on the left side of the editor, but when you open Atom it *sometimes* appears in between the tree view and the editor and sometimes on the left side of the tree view?

Probably a package load order thing. As far as I know, Atom has no real package priority system, so it just loads whatever. If this package and the tree view are both saying, "add me to the left side" on load, then Atom adds them in the order it receives the instruction.

**Comment by ShiroiKuma** [comment]
Your clarification is correct yeah. On Windows I didn't notice this, only on the OS X version so far. I just tried another 10 times and it's hit-and-miss on OS X.

It more than likely is an internal load order thing as you say, first come first served.

**Comment by DamnedScholar** [comment]
The solution might be to hold off on actually displaying the sidebar until the [onDidLoadInitialPackages](https://atom.io/docs/api/v1.8.0/PackageManager#instance-onDidLoadInitialPackages) event fires, which would effectively force the Project Viewer sidebar completely to one side.

**Comment by jccguimaraes** [comment]
hi @ShiroiKuma and @DamnedScholar,
sorry for the delay response. Indeed it is a question of ordering because adding it depends on a parameter called priority or something like that, which i think I don't set because it's automatically set to the last and in this case it's running earlier than it should.

@DamnedScholar `onDidLoadInitialPackages` seems to be the correct way to do it.

Any one of you care to **contribute**? Or I can do it, it has become a lot of lines xD
